CREATE DATABASE ce_db;

CREATE TABLE estado (
    id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    uf VARCHAR(2) NOT NULL UNIQUE
);

CREATE TABLE cidade (
    id_cidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    id_estado INTEGER NOT NULL,
    CONSTRAINT fk_cidade_estado FOREIGN KEY (id_estado) REFERENCES estado(id_estado)
);

CREATE TABLE bairro (
    id_bairro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    id_cidade INTEGER NOT NULL,
    CONSTRAINT fk_bairro_cidade FOREIGN KEY (id_cidade) REFERENCES cidade(id_cidade)
);

CREATE TABLE tipo_cliente (
    id_tipo_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(100) NOT NULL
);

CREATE TABLE cliente (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    logradouro VARCHAR(200),
    numero VARCHAR(20),
    id_bairro INTEGER,
    cep VARCHAR(9),
    id_cidade INTEGER,
    id_estado INTEGER,
    id_tipo_cliente INTEGER,
    representante VARCHAR(150),
    telefone_contato VARCHAR(30),
    email_contato VARCHAR(150),
    CONSTRAINT fk_cliente_bairro FOREIGN KEY (id_bairro) REFERENCES bairro(id_bairro),
    CONSTRAINT fk_cliente_cidade FOREIGN KEY (id_cidade) REFERENCES cidade(id_cidade),
    CONSTRAINT fk_cliente_estado FOREIGN KEY (id_estado) REFERENCES estado(id_estado),
    CONSTRAINT fk_cliente_tipo FOREIGN KEY (id_tipo_cliente) REFERENCES tipo_cliente(id_tipo_cliente)
);

CREATE TABLE tipo_produto (
    id_tipo_produto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(120) NOT NULL
);

CREATE TABLE categoria_produto (
    id_categoria_produto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(120) NOT NULL
);

CREATE TABLE unidade_medida (
    id_unidade_medida INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(100) NOT NULL,
    sigla VARCHAR(20) NOT NULL
);

CREATE TABLE produto (
    id_produto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(200) NOT NULL,
    custo_unitario NUMERIC(12, 2) NOT NULL DEFAULT 0,
    preco_venda NUMERIC(12, 2) NOT NULL DEFAULT 0,
    id_tipo_produto INTEGER,
    id_categoria_produto INTEGER,
    id_unidade_medida INTEGER,
    quantidade_por_unidade NUMERIC(12, 3),
    id_unidade_conteo INTEGER,
    CONSTRAINT fk_produto_tipo FOREIGN KEY (id_tipo_produto) REFERENCES tipo_produto(id_tipo_produto),
    CONSTRAINT fk_produto_categoria FOREIGN KEY (id_categoria_produto) REFERENCES categoria_produto(id_categoria_produto),
    CONSTRAINT fk_produto_unidade FOREIGN KEY (id_unidade_medida) REFERENCES unidade_medida(id_unidade_medida),
    CONSTRAINT fk_produto_unidade_conteo FOREIGN KEY (id_unidade_conteo) REFERENCES unidade_medida(id_unidade_medida),
    CONSTRAINT ck_produto_custo CHECK (custo_unitario >= 0),
    CONSTRAINT ck_produto_preco CHECK (preco_venda >= 0),
    CONSTRAINT ck_produto_qtd_unidade CHECK (quantidade_por_unidade IS NULL OR quantidade_por_unidade >= 0)
);

CREATE TABLE fornecedor (
    id_fornecedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    logradouro VARCHAR(200),
    numero VARCHAR(20),
    id_bairro INTEGER,
    cep VARCHAR(9),
    id_cidade INTEGER,
    id_estado INTEGER,
    representante VARCHAR(150),
    telefone_contato VARCHAR(30),
    email_contato VARCHAR(150),
    CONSTRAINT fk_fornecedor_bairro FOREIGN KEY (id_bairro) REFERENCES bairro(id_bairro),
    CONSTRAINT fk_fornecedor_cidade FOREIGN KEY (id_cidade) REFERENCES cidade(id_cidade),
    CONSTRAINT fk_fornecedor_estado FOREIGN KEY (id_estado) REFERENCES estado(id_estado)
);

CREATE TABLE produto_fornecedor (
    id_produto_fornecedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto INTEGER NOT NULL,
    id_fornecedor INTEGER NOT NULL,
    custo_unitario NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_prod_fornecedor_produto FOREIGN KEY (id_produto) REFERENCES produto(id_produto),
    CONSTRAINT fk_prod_fornecedor_fornecedor FOREIGN KEY (id_fornecedor) REFERENCES fornecedor(id_fornecedor),
    CONSTRAINT uq_produto_fornecedor UNIQUE (id_produto, id_fornecedor),
    CONSTRAINT ck_prod_fornecedor_custo CHECK (custo_unitario >= 0)
);

CREATE TABLE lote (
    id_lote INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto INTEGER NOT NULL,
    id_fornecedor INTEGER NOT NULL,
    data_fabricacao DATE,
    data_validade DATE,
    quantidade_produzida NUMERIC(14, 3) NOT NULL DEFAULT 0,
    CONSTRAINT fk_lote_produto FOREIGN KEY (id_produto) REFERENCES produto(id_produto),
    CONSTRAINT fk_lote_fornecedor FOREIGN KEY (id_fornecedor) REFERENCES fornecedor(id_fornecedor),
    CONSTRAINT ck_lote_quantidade CHECK (quantidade_produzida >= 0),
    CONSTRAINT ck_lote_datas CHECK (data_validade IS NULL OR data_fabricacao IS NULL OR data_validade >= data_fabricacao)
);

CREATE TABLE estoque (
    id_estoque INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lote INTEGER NOT NULL UNIQUE,
    quantidade_atual NUMERIC(14, 3) NOT NULL DEFAULT 0,
    CONSTRAINT fk_estoque_lote FOREIGN KEY (id_lote) REFERENCES lote(id_lote),
    CONSTRAINT ck_estoque_quantidade CHECK (quantidade_atual >= 0)
);

CREATE TABLE pedido_venda (
    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL,
    data_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valor_total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT ck_pedido_valor CHECK (valor_total >= 0)
);

CREATE TABLE itens_pedido_venda (
    id_item INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL,
    id_produto INTEGER NOT NULL,
    quantidade NUMERIC(14, 3) NOT NULL,
    valor_unitario NUMERIC(12, 2) NOT NULL,
    valor_total NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_item_pedido FOREIGN KEY (id_pedido) REFERENCES pedido_venda(id_pedido),
    CONSTRAINT fk_item_produto FOREIGN KEY (id_produto) REFERENCES produto(id_produto),
    CONSTRAINT ck_item_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_item_valor_unitario CHECK (valor_unitario >= 0),
    CONSTRAINT ck_item_valor_total CHECK (valor_total >= 0)
);

CREATE TABLE metodo_pagamento (
    id_metodo_pagamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(100) NOT NULL
);

CREATE TABLE pagamento (
    id_pagamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL,
    id_metodo_pagamento INTEGER NOT NULL,
    valor NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_pagamento_pedido FOREIGN KEY (id_pedido) REFERENCES pedido_venda(id_pedido),
    CONSTRAINT fk_pagamento_metodo FOREIGN KEY (id_metodo_pagamento) REFERENCES metodo_pagamento(id_metodo_pagamento),
    CONSTRAINT ck_pagamento_valor CHECK (valor >= 0)
);

CREATE TABLE tipo_movimentacao_estoque (
    id_tipo_movimentacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(100) NOT NULL,
    tipo VARCHAR(30) NOT NULL
);

CREATE TABLE movimentacao_estoque (
    id_movimentacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lote INTEGER NOT NULL,
    id_tipo_movimentacao INTEGER NOT NULL,
    quantidade NUMERIC(14, 3) NOT NULL,
    data_movimentacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mov_estoque_lote FOREIGN KEY (id_lote) REFERENCES lote(id_lote),
    CONSTRAINT fk_mov_estoque_tipo FOREIGN KEY (id_tipo_movimentacao) REFERENCES tipo_movimentacao_estoque(id_tipo_movimentacao),
    CONSTRAINT ck_mov_estoque_quantidade CHECK (quantidade > 0)
);

-- Índices para colunas de relacionamento consultadas com frequência.
CREATE INDEX idx_cliente_bairro ON cliente(id_bairro);
CREATE INDEX idx_cliente_tipo ON cliente(id_tipo_cliente);
CREATE INDEX idx_produto_categoria ON produto(id_categoria_produto);
CREATE INDEX idx_lote_produto ON lote(id_produto);
CREATE INDEX idx_lote_fornecedor ON lote(id_fornecedor);
CREATE INDEX idx_pedido_cliente ON pedido_venda(id_cliente);
CREATE INDEX idx_item_pedido ON itens_pedido_venda(id_pedido);
CREATE INDEX idx_pagamento_pedido ON pagamento(id_pedido);
CREATE INDEX idx_movimentacao_lote ON movimentacao_estoque(id_lote);
